In [2]:
import pandas as pd
import numpy as np
import geopandas as gpd
from bs4 import BeautifulSoup
import h3
from shapely.geometry import Polygon

In [3]:
from dotenv import load_dotenv
import os

# Load the environment variables from .env file
load_dotenv()

from supabase import create_client, Client

url: str = os.environ.get("SUPABASE_URL")
key: str = os.environ.get("SUPABASE_KEY")
supabase: Client = create_client(url, key)

In [4]:
properties_df = pd.read_parquet('../data/L3/propeties.parquet')
nearby_df = pd.read_parquet('../data/L3/nearby_facilities.parquet')
hdb_df = pd.read_parquet('../data/L3/hdb_transaction.parquet')
private_df = pd.read_parquet('../data/L3/private_transaction.parquet')
listing_sales = pd.read_parquet('../data/L3/listing_sales.parquet')

In [6]:
nearby_df

,property_index,type,name,distance_m
0,affinity at serangoon,preschool,Little Footprints Preschool Group Pte Ltd,1281.873195
0,affinity at serangoon,kindergarden,PCF Sparkletots Preschool @ Serangoon Blk 226 ...,1092.384876
0,affinity at serangoon,preschool,PCF Sparkletots Preschool @ Serangoon Blk 226 ...,1092.384876
0,affinity at serangoon,preschool,PCF Sparkletots Preschool @ Serangoon Blk 226 (KN,1092.384876
0,affinity at serangoon,preschool,ROSYTH CHILD CARE CENTRE,1047.524303
...,...,...,...,...
0,alkaff vista,preschool,MY FIRST SKOOL,732.853407
0,alkaff vista,supermarket,HAO MART PTE. LTD.,1070.426592
0,alkaff vista,preschool,SPRING BRAINY KIDZ (POTONG PASIR) PTE. LTD.,1064.142364
0,alkaff vista,preschool,IDEAL MONTESSORI PTE LTD,741.291357
0,alkaff vista,hawker,Woodleigh Village Hawker Centre,717.057015

In [5]:
properties_df

,property_index,blk_no,road_name,building,address,postal
0,AFFINITY AT SERANGOON SERANGOON NORTH AVENUE 1,26,SERANGOON NORTH AVENUE 1,AFFINITY AT SERANGOON,26 SERANGOON NORTH AVENUE 1 AFFINITY AT SERANG...,554340
0,THE FLORENCE RESIDENCES HOUGANG AVENUE 2,83,HOUGANG AVENUE 2,THE FLORENCE RESIDENCES,83 HOUGANG AVENUE 2 THE FLORENCE RESIDENCES SI...,538860
0,THE GARDEN RESIDENCES SERANGOON NORTH VIEW,5,SERANGOON NORTH VIEW,THE GARDEN RESIDENCES,5 SERANGOON NORTH VIEW THE GARDEN RESIDENCES S...,554345
0,THE PROMENADE@PELIKAT JALAN PELIKAT,183,JALAN PELIKAT,THE PROMENADE@PELIKAT,183 JALAN PELIKAT THE PROMENADE@PELIKAT SINGAP...,537643
0,PRIMO RESIDENCES JALAN PELIKAT,137,JALAN PELIKAT,NIL,137 JALAN PELIKAT SINGAPORE 537620,537620
...,...,...,...,...,...,...
0,457B SENGKANG WEST RD,457B,SENGKANG WEST ROAD,FERNVALE WOODS,457B SENGKANG WEST ROAD FERNVALE WOODS SINGAPO...,792457
0,106B BIDADARI PK DR,106B,BIDADARI PARK DRIVE,ALKAFF VISTA,106B BIDADARI PARK DRIVE ALKAFF VISTA SINGAPOR...,342106
0,458B SENGKANG WEST RD,458B,SENGKANG WEST ROAD,FERNVALE WOODS,458B SENGKANG WEST ROAD FERNVALE WOODS SINGAPO...,792458
0,105A BIDADARI PK DR,105A,BIDADARI PARK DRIVE,ALKAFF VISTA,105A BIDADARI PARK DRIVE ALKAFF VISTA SINGAPOR...,341105
0,106A BIDADARI PK DR,106A,BIDADARI PARK DRIVE,ALKAFF VISTA,106A BIDADARI PARK DRIVE ALKAFF VISTA SINGAPOR...,341106

In [3]:

table = pq.read_table('data.parquet')
json_data = table.to_pandas().to_json(orient='records')

# Insert JSON data into Supabase
response = supabase.table('your_table_name').insert(json.loads(json_data)).execute()
print(response)